title: <p align="center"> Apoorv Bafna </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://https://www.linkedin.com/in/apoorv-bafna-085a38106/">LinkedIn</a> |
  <a href="https://github.com/apoorvbafna">GitHub</a>
  
  <br>   
  I'm studying Data Science, Big Data & Machine learning. 

  <br>
  </p>



theme: jekyll-theme-minimal
